### PR TITLE
Addwindows

### PR DESCRIPTION
**Pull request by vizPilot**

### CODE REVIEW

**Comment by marohinmark** [comment]
Is this April Fools loool? This just breaks all

**Comment by vizPilot** [comment]
Not because is for install Windows

**Comment by marohinmark** [comment]
I have a fix of not compiling edk2

сб, 16 окт. 2021 г., 23:43 Vicente Cortes ***@***.***>:

**Comment by marohinmark** [comment]
Screenshot_20211017-120857
There should be only one blocksize and only one numblocks.

**Comment by marohinmark** [comment]
That's why it doesn't compile. Also there is a problem with GUID and path to one of the windows boot files.

**Pull request closed without merging**
